services:
  db:
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
  
  minio:
    volumes:
      - minio_data_local:/data
  
  backend:
    env_file:
      - ".env.local"

  nginx:
    ports:
      - "5000:80"
    environment:
      - NGINX_PORT: 80
      - SSL_ENABLED: "false"
      - HSTS_MAX_AGE: 60
      - RATE_LIMIT_ENABLED: "false"

volumes:
  postgres_data_local:
  minio_data_local: