services:
  backend:
    env_file:
      - ..env.test

  nginx:
    ports:
      - "5000:80"
    environment:
      - NGINX_PORT: 80
      - SSL_ENABLED: "false"
      - HSTS_MAX_AGE: 60
      - RATE_LIMIT_ENABLED: "false"