services:
  db:
    image: postgres:18-alpine
    restart: always
    environment:
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      - POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - db_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    restart: always
    environment:
      - MINIO_ROOT_USER: ${MINIO_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD: ${MINIO_SECRET_ACCESS_KEY}
      - MINIO_SERVER_URL: "http://${MAIN_DOMAIN}/s3"
      - MINIO_BROWSER: off
    networks:
      - minio_net
      - minio_public_net
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MINIO_PORT}/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: final
    restart: always
    env_file:
      - ..env.local
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - backend_net
      - db_net
      - minio_net

  # frontend_main placeholder

  frontend_admin:
    build:
      context: ./frontend/admin
      dockerfile: Dockerfile
      target: final
    restart: always
    networks:
      - frontend_admin_net

  nginx:
    image: nginx:1.29
    restart: always
    ports:
      - "5000:80"
    volumes:
      - ./nginx/templates/variables.conf.template:/etc/nginx/templates/variables.conf.template:ro
      - ./nginx/includes:/etc/nginx/includes:ro
      - ./nginx/conf.d/default-http.conf:/etc/nginx/conf.d/default-http.conf:ro
      - ./nginx/conf.d/default-https.conf:/etc/nginx/conf.d/default-https.conf:ro
      - ./nginx/error-sites:/usr/share/nginx/html/errors:ro
      - ./nginx/ssl/certificates:/etc/nginx/ssl:ro
    environment:
      # NGINX config
      - NGINX_HOST: ${MAIN_DOMAIN}
      - NGINX_PORT: 80
      - RATE_LIMIT_ENABLED: "false"
      - UPLOAD_FILE_MAX_SIZE: 50m
      # SSL
      - SSL_ENABLED: "false"
      - SSL_CERT_NAME: "example.crt"
      - SSL_KEY_NAME: "example.key"
      - HSTS_MAX_AGE: 60
      # Services
      - MINIO_HOST: "${MINIO_HOST}:${MINIO_PORT}"
      - MINIO_CONSOLE_HOST: "${MINIO_HOST}:9001"
      - BACKEND_API_HOST: "backend:${API_PORT}"
      - FRONTEND_MAIN_HOST: "frontend_main:80"
      - FRONTEND_ADMIN_HOST: "frontend_admin:80"
    networks:
      - minio_public_net
      - backend_net
      - frontend_admin_net
    depends_on:
      - backend
      - frontend_admin
    command: >
      /bin/sh -c "
        envsubst '
          ${NGINX_HOST}
          ${NGINX_PORT}
          ${RATE_LIMIT_ENABLED}
          ${UPLOAD_FILE_MAX_SIZE}
          ${SSL_ENABLED}
          ${SSL_CERT_NAME}
          ${SSL_KEY_NAME}
          ${HSTS_MAX_AGE}
          ${MINIO_HOST}
          ${MINIO_CONSOLE_HOST}
          ${BACKEND_API_HOST}
          ${FRONTEND_MAIN_HOST}
          ${FRONTEND_ADMIN_HOST}
        ' < /etc/nginx/templates/variables.conf.template \
          > /etc/nginx/includes/variables.conf &&
        if [ \"$SSL_ENABLED\" != \"true\" ]; then
          rm -f /etc/nginx/conf.d/default-https.conf;
        fi &&
        nginx -g 'daemon off;'
      "

networks:
  db_net:
  minio_net:
  minio_public_net:
  backend_net:
  frontend_main_net:
  frontend_admin_net: